# Site
title: Michael Standen
description: Check out the ramblings and open source projects by Michael Standen, a software engineer for fun and profit.
url: https://michael.standen.link
logo: dp_round.webp
disqus_shortname: michael-standen
locale: en_US

# Left Block Images
background:
  homepage: images/oqtafyt5ktw-ilya-pavlov.webp
  post-list: images/escc1qx6tvw-ehud-neuhaus.webp
  default-post: images/1ivkwelwrpa-patrick-lindenberg.webp

# Jekyll
permalink:          date
markdown:           kramdown
highlighter:        rouge
kramdown:
  auto_ids:         true
  footnote_nr:      1
  entity_output:    as_char
  toc_levels:       1..6
  enable_coderay:   false
sass:
  sass_dir:         assets/_sass
  style:            compressed

# Google Analytics
google-analytics: UA-64252817-1

# Social Links
#email:              michael@standen.link
google.plus:        +MichaelStanden
twitter:            _MichaelStanden
#facebook:           username
github:             ScreamingHawk
stackoverflow:      2027146/milk
linkedin:           michael-standen-ab1436bb
#xing:               username
#instagram:          username
#lastfm:             username
#tumblr:             username
#pinterest:          username
#foursquare:         username
#steam:              username
#dribbble:           username
#youtube:            username
#soundcloud:         username
#weibo:              username
#flickr:             username
#codepen:            username
#keybase:            username
#xmpp:               username@server.com
#hackernews:         username
#behance:            username

# Gems
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-gist

# Exclude list
include:
  - _pages
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - _site
  - src
  - vendor
  - CNAME
  - LICENSE
  - THEME_LICENSE
  - Rakefile
  - .sass-cache
  - .DS_Store
  - build.sh
  - deploy.sh
  - serve.sh
  - node_modules
  - package.json
  - package-lock.json
